#+AUTHOR: vab2048
#+TITLE: My .emacs.d configuration

This repo contains my (semi) organised .emacs.d configuration. When initialising, Emacs looks
for:

1. =~/.emacs= (which I do not use)
2. =~/.emacs.el= (which I do not use)
3. =~/.emacs.d/init.el= (which is contained in this repo)

I've tried to be organised by using org mode to document everything. There is still some cruft
left over from before I used a =~.emacs.d= directory and was using a =.emacs= file but
essentially the control flow is as follows: 

1. =~/.emacs.d/init.el= is loaded
2. =~/.emacs.d/init.el= contains the following emacs lisp:
   #+BEGIN_SRC emacs-lisp
   (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
   (load custom-file)
   #+END_SRC
   - ~custom.el~ contains the emacs-lisp that is output when you use emacs' own UI to customise
     variables. This code just loads that file.
3. =~/.emacs.d/init.el= also contains the following emacs lisp:
   #+BEGIN_SRC emacs-lisp
     ;; load the Emacs Lisp source code blocks in the given Org-mode <file>.
     (org-babel-load-file (concat user-emacs-directory "config.org"))
   #+END_SRC
   - This essentially loads ~config.org~, extracts all source blocks which are labeled as
     having the language ~emacs-lisp~, puts them into a file, ~config.el~, and runs the code in
     that file.

That's basically it. 

* Common Problems

** Incompatible .elc files

Using compiled =.elc= files which were compiled for a previous/different version of emacs may
result in issues.  This is because "packages are all bytecode compiled upon installation, so
it's not so far fetched that they are bound to a particular version of Emacs after that." So we
need to make sure the byte compiled files (i.e. .elc) are removed from the .emacs.d folder the
first time you initialise the config on a new machine.

Steps:
1. Copy the .emacs.d folder from the old home directory to the new.
2. Remove the byte compiled files from the .emacs.d directory (example script below)

#+BEGIN_SRC sh
# To remove the .elc files from the .emacs.d directory
cd ~/.emacs.d
find ./ -name "*.elc" -delete
#+END_SRC

On Windows you can search the .emacs.d folder for "*.elc", sort by file type and delete all entries
for elc file.


